### ISSUE TITLE
Workflow error: Semantic release failure

### ISSUE THREAD

**Issue by jeswr** [LDflex/async-iteration-handlers#13]
Semantic release is [failing](https://github.com/LDflex/async-iteration-handlers/runs/2039365000) I believe this is because I am not a member of the LDflex organisation on NPM and so cannot publish under the `@ldflex` scope.

@RubenVerborgh Could you please either update the `NPM_TOKEN` [here](https://github.com/LDflex/async-iteration-handlers/settings/secrets/actions) to one of your automation tokens, or add me as a member (my username is also jeswr on NPM) to the LDflex organisation on NPM so that I have publishing rights.

**Comment by RubenVerborgh** [comment]
Invited you!

**Comment by jeswr** [comment]
Doesn't appear to have come through. Perhaps try using adding by email (jmwright.045@gmail.com) instead?

**Comment by RubenVerborgh** [comment]
@jeswr Done!
